export const selectionObject: any = {
  roll_no: false,
  first_name: false,
  last_name: false,
  middle_name: false,
  email: false,
  phone_number: false,
  gender: false,
  github: false,
  linkedin: false,
  no_of_offers: false,
  department: false,
  batch: false,
  rait_email: false,
};

export const beautifulLabels: any = {
  roll_no: 'Roll No',
  first_name: 'First Name',
  last_name: 'Last Name',
  middle_name: 'Middle Name',
  email: 'Email',
  phone_number: 'Phone Number',
  gender: 'Gender',
  github: 'Github',
  linkedin: 'Linkedin',
  no_of_offers: 'No of offers',
  department: 'Department',
  batch: 'Batch',
  rait_email: 'Rait Email',
};
